### PR TITLE
New Tufte inspired site design.

### PR DESCRIPTION
**Pull request by jvaverka**
As discussed in [this discourse thread](https://discourse.julialang.org/t/book-parallel-computing-and-scientific-machine-learning-sciml-methods-and-applications/75509/6?u=jvaverka), this pull request will make the necessary changes to achieve a new site design inspired by [Tufte-CSS](https://edwardtufte.github.io/tufte-css/) and using the official Julia language color palette.

Here is a [preview](https://jvaverka.github.io/NewSciMLBook/) of the new site.

### CODE REVIEW

**Comment by jvaverka** [comment]
Looks like just a couple steps still required for Github Pages. 

https://franklinjl.org/workflow/deploy/#deploying_on_github

**Comment by ChrisRackauckas** [comment]
Gave you permissions to do what's necessary.

**Comment by tlienart** [comment]
Nice one, thanks @jvaverka

**Comment by RoyiAvital** [comment]
It would be great to have the menu on the left floating with the scroll. Also to have some indication on it on which element you're.

**Comment by ChrisRackauckas** [comment]
open an issue.

**Pull request merged**
